### ISSUE TITLE
Duplicate users can be created on the login page when clicking add user

### ISSUE THREAD

**Issue by joncodo** [friggframework/create-frigg-app#30]
I realize that this is likely just demo code but this can easily break the flow for a new user.

## What is going wrong
You can keep clicking the create user button and it makes duplicate users. 
When you try to login, login fails if more than one user in the db has the same email

## Possible Solution
We need a unique field on email so this can’t happen and a flow to tell the user that the email already registered

## Steps to reproduce:
- Run the create-frigg-application and see the login page for the first time
- Click create user
- Login
- See that everything works
- Log out
- Click create user a few times
- See in your DB that many users exist now and no eros were thrown
- Try to log in again
- Login fails
- Delete all users from your DB except one
- Login and see that it works again

**Comment by seanspeaks** [comment]
Agreed. Pretty "easy" fix, though implications to be considered when it comes to user management in a Frigg application.


⚙⚙⚙⚙⚙⚙⚙⚙⚙⚙


Sean Matthews


Co-Founder & Frigg Lead Developer
LeftHook.com & FriggFramework.org




& 

--- original message ---
On January 9, 2023 at 10:02 AM EST ***@***.*** wrote:



I realize that this is likely just demo code but this can easily break the flow for a new user.

What is going wrong

You can keep clicking the create user button and it makes duplicate users.

When you try to login, login fails if more than one user in the db has the same email

Possible Solution

We need a unique field on email so this can’t happen and a flow to tell the user that the email already registered

Steps to reproduce:

Run the create-frigg-application and see the login page for the first time

Click create user

Login

See that everything works

Log out

Click create user a few times

See in your DB that many users exist now and no eros were thrown

Try to log in again

Login fails

Delete all users from your DB except one

Login and see that it works again


—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
--- end of original message ---

**Comment by joncodo** [comment]
There are two ways I can see this being "fixed"

The "Create account (demo user)" button is really only there for test purposes. For this reason, maybe we can handle this in better ways. 

1. We don't care too much about this button. We just remove it once you click on it the first time from the ui. 
2. We could also check on frontend application load to see if there is a user in the DB already for demo. If not, create it for the user from the backend. This means we do not force the user to click this button to be able to log in on first application launch.
3. We care and want to force all users created to be unique in the DB since login requires a uniques DB record to be found. For this, we will update the models and provide a better message on the front end that says something like: "user already exists"

I am going for option 3 unless @seanspeaks has other ideas. Please approve before I do this work 🌵

**Comment by seanspeaks** [comment]
@joncodo The tension I have with building a more robust user model and flow (routes, db logic, error handling, etc) is that the "best" approach to adopting Frigg is to remove the lightweight user management piece and _just_ go with a to-be-default/normalized header regimen of `x-frigg-appUserId` and `x-frigg-appOrgId`, which correspond to individualUser and organizationUser models. 

The Frigg adopter would pretty quickly remove the user router and we probably want to remove details around username and hashword... Frigg is intended to "bolt on" to the adopter's existing software, which presumably has all of the user management it needs and all of the user details; so Frigg just cares about IDs.

We could cut a third model here, and call it "devUser" or something else to indicate that this is intended to be a throwaway model and router? And therefore UI flow? And put your fixes there?

There _may_ be some adopters who want to user Frigg as a standalone "product" outside of their core software product (I can imagine a "Software X Integrations.com", something like that) so that they don't have to get the core product team to do _any_ development... then the adopter would need a more robust user management.

Let me know what you think/if you think a working example of the "desired end state" would be helpful, or a diagram to conceptualize further?

**Comment by joncodo** [comment]
Well if the backend is the main product and the front end is not really intended to be used a lot, I ask what the purpose of the front end is?

The business use case  I can see for the frontend is to deploy a frigg application from create-frigg-app and host it for developers to add and manage integrations. Having said that, I don't think that is likely since it exposes a configuration tool that may not be that secure. IE: if someone wants to hurt a company that uses Frigg, they can attack the front end where we have not put too much time into security. Maybe this is a risk, maybe it is not.

Since most people that use this framework will be using only the backend, (Including us), Maybe we need to re-jig this to only be backend? 

If you really want to keep the front end, I suggest we add an option to create-frigg-app to omit the front end when generating code.

If we want to keep it as is, I suggest we do this 

> We don't care too much about this button. We just remove it once you click on it the first time from the ui.

**Comment by joncodo** [comment]
The main problem I am trying to address with this ticket is related to a new user that is trying to adopt Frigg. In that case, it is all too easy to click create user twice when you think there is an error or something. Because this creates a duplicate user, you can never log in until you fix the data in your DB. This is a pretty easy pitfall for new adopters that will turn a percentage of them away I think 😅

**Comment by joncodo** [comment]
bump @seanspeaks

**Comment by seanspeaks** [comment]
Three thoughts:
1. I like the idea of optional frontend install. The hope/goal is that you need _some_ sort of frontend to understand how the app works and how you might incorporate into your existing application, but that it would likely be a throwaway part of the code. The other important part (not mentioned here yet) is that we have frontend needs for integrations where you're allowed to call in an iFrame or html/js/css code (bring-your-own-framework, just point to a valid URL) (Front, Zendesk, HubSpot's "Advanced IFRAME actions", Salesforce, etc.). Those aren't needed for any "getting started", but it's a nice option to have UI's dedicated to integrations be managed in the same place that the backend/business logic is managed.
2. Hiding the link post create is a-okay by me. There's some fiddling we can do with the Model/collection/uniqueness to reject creation attempts of existing user info, but, that's probably best handled separately.
3. The end-goal of the frontend is to have it actually importing and exercising a proper React/Vue/Angular/Generic Web UI Library that any team can leverage to just "plug and play" with their Frigg implementation. So these components would be bundled up together and then a dev team can choose to take some, none, or all of the components to plug in nicely alongside the Frigg Management API

Does that help guide? Summary on action: hide the button, make the installation of the frontend optional.

One other new "Use Case" to call out/carve out into either this repo or the core or the docs: To actually integrate Frigg into your application well, I've settled on a default approach of having all Management API requests expect `x-Frigg-appUserId` and `x-Frigg-appOrgId` headers, which invokes the `loadUserManager` middleware, which `finds or creates` the provided users by corresponding ID. "App" in this case is "your app".

**Comment by joncodo** [comment]
Closed in favout of #49 #50 and #51
