### ISSUE TITLE
Remove dependency on MongoDB Atlas

### ISSUE THREAD

**Issue by joncodo** [friggframework/create-frigg-app#43]
There are a few things that make Mongo Atlas tough to work with for new users.

1. You have to create an account and set up a database
2. If your IP address changes, you get this error: `[0] MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/` Which is not easily evident to solve though it can be fixed.
3. When working with the DB, you need to manage it in Atlas.

I suggest we use a locally hosted instance of mongo with docker-compose or use [mongo in memory](https://github.com/nodkz/mongodb-memory-server)

Then we have a section in the docs on how to use Atlas if that is what you want. I just think Atlas adds friction for new users.

Thoughts?

**Comment by joncodo** [comment]
Another idea here. What if we have a free instance of the DB that can be shared between all users to just get up and running and all data is deleted in that DB each day?

**Comment by seanspeaks** [comment]
I meant to reply to this:
I'm agnostic. I find Atlas easiest to use, because I haven't really used Docker prior. And I like the GUI. (Side note, adding 0.0.0.0 to just allow public access is fine for test DBs, I usually do that for one-offs)

But, it makes sense to me that we would have some short sections or links out to "Getting started with MongoDB Atlas", "Docker", "Mongo in memory". All that's needed is a working/valid MONGO_URI

RE: the shared DB, I'm not sure how to guard against abuse, since that free DB would need to provision credentialed access.

**Comment by joncodo** [comment]
Ok. Well I think the drawbacks of this is that you have to understand Atlas. This is the largest step for us for new developers that is not related to our code base. 

I recommend we change the docs to show two ways of maintaining urls. One is with docker-compose since it takes very few steps and another is with Atlas.

Approved @seanspeaks ?

**Comment by seanspeaks** [comment]
Sure, we might not even want to go into too much detail for either, just point to the docs for each?

**Comment by joncodo** [comment]
Docs updated. Done.
