### ISSUE TITLE
Use case 1: Engineering Manager who needs a lot of integrations built

### ISSUE THREAD

**Issue by joncodo** [friggframework/create-frigg-app#47]
## User Story

**"how can we get all of these things built with the resources we have?"**

## Summary 

What Frigg enables for this person is the ability to look externally for engineering help with external APIs.
- Instead of having their core engineering learn an external API and its nuances/intricacies once, they can either leverage the ever-increasing value of Frigg abstractions, 
- or they can hire an external team to contribute their knowledge just to an isolated integration codebase (so, they don't need a contractor to have access to their core code/they can just hire expertise in a specific application/marketplace/ecosystem). 
- Or they can combine approaches. 
- The point here is that leveraging Frigg is beneficial for what it unlocks with getting external expertise in the door to help.

## Questions 
1. @seanspeaks, do you meant to say that the external expertise is hiring lefthook to build things for them? Or just that the code is open source and has been developed, therefore it saves time?
> "what it unlocks with getting external expertise in the door to help"

2. @seanspeaks when Frigg is all done and perfect, 😉 , is the intent that consumers of Frigg will very rarely need to read the docs of the APIs that they are interfacing with since all the code will interface with all APIs in the same way?

**Comment by seanspeaks** [comment]
1. Well, right now, it's Left Hook because we're really the only ones who have the combined "Frigg plus target API" knowledge. The whole purposes of open sourcing it is to garner experts from around the world, from around the different ecosystems, to pick up and try to nurture along their part of Frigg's library. At some point, the idea is that through that gained expertise, common helper functions, testing harness, scaffolding tools, code patterns, and schema validation should allow someone who hasn't ever touched the HubSpot API docs (for example) to quickly build a HubSpot App that has some HubSpot-specific features built in (CRM Extensions, Timeline Events, Workflows, Custom Schemas, etc)
2. That's certainly the end goal, though the hope/idea is that you can "get started quickly" and then break out of any sort of abstraction or training wheels if you need to get into the weeds for whatever reason. 

Expanding on #2 a bit... and this _really_ should go in Core Frigg, API module development notes... I want to have all APIs broken down by Resources and their Schemas, and corresponding Verbs/Methods. I'm leaning towards something like:
`listResource` = returns array
`getResource` = returns an object, probably with query filters/options
`getResourceById` returns an object expects ID
`updateResource`, `createResource`, `deleteResource` (normal CRUD)
`someResourceSpecificMethod` = i.e. "sendEmail", "pauseWorkflow", "startWorkflow" etc.
and each one is explorable by both exposed Types and by a common interface such that we could build out easy helper tooling "Select a resource to find out what it can do", "Explore a resource in more details, including fields, events, common workflows", "here are the most popularly used methods"

When you combine that ^^ with auth "figured out for you" and normalized developer notes on how to get started... it'd be like an Integration Dev Cookbook

**Comment by joncodo** [comment]
Added to docs. Great stuff!
